# User config
author: "Sandra Cortijo"
tagline: "SrtKnowles"
description: "Hola!! Bienvenida a mi galeria✨✨"
keywords: "Gallery, Portfolio, Art"
email: "sandramakingart@gmail.com"
redbubble: "https://www.redbubble.com/people/srtknowles/shop"
instagram: "https://www.instagram.com/sandramakesart/"
url: "https://sancortijo.netlify.app/"

# Developer
developerGH: "https://github.com/mavilam"

# Site config
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
