backend:
  name: github
  repo: mavilam/sancortijo.github.io # Branch to update (optional; defaults to master)
  api_root: https://api.github.com
  site_domain: https://mavilam.github.io/sancortijo.github.io/
  base_url: https://api.netlify.com 
  auth_endpoint: auth

media_folder: "assets/images/projects" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI
    folder: "_posts/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "permalink", name: "permalink", widget: "hidden", default: "/:title/"}
      - {label: "category", name: "category", widget: "hidden", default: "projects"}
      - {label: "Title", name: "title", widget: "string"}
